services:
  - name: accounts
    type: web
    env: python
    repo: https://github.com/NewCodeCrafters/ncc-task-management-backend/tree/auth-base
    branch: main  # Change to the branch you want to deploy
    buildCommand: "./build.sh"
    startCommand: "gunicorn accounts.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
