# Generated by Django 5.1.3 on 2025-04-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.DateTimeField(),
        ),
    ]
